# Generated by Django 4.0.4 on 2022-06-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
    ]
