# Generated by Django 4.0.4 on 2022-06-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_profile_profile_pic_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
