# Generated by Django 4.0.4 on 2022-06-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_review_review_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project.project'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
